In [30]:
#necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
def safelog(x):
    return(np.log(x + 1e-100))

In [31]:
def safelog(x):
    return(np.log(x + 1e-100))

In [32]:
images= np.loadtxt("hw02_data_set_images.csv",delimiter = ",") 
labels = np.loadtxt("hw02_data_set_labels.csv").astype(int)

In [33]:
data = np.array(list(zip(images,labels))) # zipped together for further export

# extraction of data training and test sets from data
training_set = np.array([data[labels == c + 1][:25] for c in range(5)])
test_set = np.array([data[labels == c+ 1][25:] for c in range(5)])
training_set = np.concatenate(training_set)
test_set = np.concatenate(test_set)

In [34]:
# preprocessing
x_training = np.concatenate(training_set[:,0].reshape(125,1),)
y_training = np.stack(training_set[:,1])
x_test = np.concatenate(test_set[:,0].reshape(70,1),)
y_test = np.stack(test_set[:,1])


In [35]:
class_priors = np.array([np.mean(y_training==c + 1) for c in range(5)]) # class frequency in training data set
pcd = np.array([np.mean(x_training[y_training==c +1]) for c in range(5)]) # class means for an image

In [36]:
print(pcd)

[[0.   0.   0.   ... 0.68 0.68 0.64]
 [0.04 0.24 0.24 ... 0.8  0.56 0.24]
 [0.   0.   0.   ... 0.6  0.88 0.8 ]
 [0.12 0.44 0.4  ... 0.28 0.16 0.08]
 [0.   0.12 0.12 ... 0.32 0.48 0.44]]


In [37]:
print(class_priors)

[0.2 0.2 0.2 0.2 0.2]


In [40]:
# prediction or naive bayes classifier
# directly returns predicted class labels
def prediction_for_x(x,pcd,class_priors):
    
    score_for_1 = np.sum([x[d]*safelog(pcd[0][d]) + (1-x[d])*safelog(1-pcd[0][d]) for d in range(len(x))]) + np.log(class_priors[0])
    score_for_2 = np.sum([x[d]*safelog(pcd[1][d]) + (1-x[d])*safelog(1-pcd[1][d]) for d in range(len(x))]) + np.log(class_priors[1])
    score_for_3 = np.sum([x[d]*safelog(pcd[2][d]) + (1-x[d])*safelog(1-pcd[2][d]) for d in range(len(x))]) + np.log(class_priors[2])
    score_for_4 = np.sum([x[d]*safelog(pcd[3][d]) + (1-x[d])*safelog(1-pcd[3][d]) for d in range(len(x))]) + np.log(class_priors[3])
    score_for_5 = np.sum([x[d]*safelog(pcd[4][d]) + (1-x[d])*safelog(1-pcd[4][d]) for d in range(len(x))]) + np.log(class_priors[4])
    
    return np.argmax(np.array([score_for_1,score_for_2,score_for_3,score_for_4,score_for_5])) + 1
        
        
        
    

In [41]:
# a classifier for any given data set 
def prediction_for_X(X,pcd,class_priors):
    prediction = []
    for i in X:
        prediction.append(prediction_for_x(i,pcd,class_priors))
    return np.array(prediction)

In [42]:
# prediction for training
predicted = prediction_for_X(x_training,bypassed_pcd,class_priors)

In [43]:

confusion_matrix = pd.crosstab(predicted,y_training,rownames = ["y_pred"],colnames = ["y_truth"])
print(confusion_matrix)

y_truth   1   2   3   4   5
y_pred                     
1        25   0   0   0   0
2         0  24   1   0   1
3         0   0  24   0   0
4         0   1   0  25   0
5         0   0   0   0  24


In [44]:
# prediction for test set
predicted_test = prediction_for_X(x_test,bypassed_pcd,class_priors)
confusion_matrix_test = pd.crosstab(predicted_test,y_test,rownames = ["y_pred"],colnames = ["y_truth"])
print(confusion_matrix_test)

y_truth  1   2  3   4   5
y_pred                   
1        7   0  0   0   0
2        0  11  3   2   4
3        0   0  7   0   0
4        7   3  3  12   0
5        0   0  1   0  10
